# Name constants
GAME_STATE_DIDNT_TAKE_TURN = 'gs-didnt-take-turn'
GAME_STATE_PLAYER_DEAD = 'gs-dead'
GAME_STATE_PLAYING = 'gs-playing'
GAME_STATE_VICTORY = 'gs-victory'

ACTION_CANCELLED = 'cancelled'

# Value constants
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50
LIMIT_FPS = 60

CAMERA_WIDTH = 80
CAMERA_HEIGHT = 43

FOV_ALGO = 0
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 20

BAR_WIDTH = 20
PANEL_HEIGHT = 7
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

INVENTORY_WIDTH = 50

CUTTING_LASER_RANGE = 3

LEVEL_UP_BASE = 200
LEVEL_UP_FACTOR = 150
LEVEL_SCREEN_WIDTH = 40

CHARACTER_SCREEN_WIDTH = 30

MAP_WIDTH = 150
MAP_HEIGHT = 150

ROOM_MAX_SIZE = 40
ROOM_MIN_SIZE = 20
MAX_ZONE_GEN_ATTEMPTS = 100
MAX_ZONES = 9

TIME_IN_TURN = 100

SATELLITES_PER_LEVEL = [[20, 1], [15, 3], [10, 5], [30, 9]]

SCOUT = 'scout'
FIGHTER = 'fighter'
GUNSHIP = 'gunship'
FRIGATE = 'frigate'
DESTROYER = 'destroyer'
CRUISER = 'cruiser'
CARRIER = 'carrier'
DIPLOMAT = 'diplomat'

# Items
ITEM_DUCT_TAPE = 'duct tape'
REPAIR_AMOUNT = 10

ITEM_EXTRA_BATTERY = 'battery'
BATTERY_POWER = 20
BATTERY_DURATION = 450

ITEM_RED_PAINT = 'red paint'

ITEM_EMP = 'EMP device'
AREA_DISABLE_TURNS = 10
AREA_DISABLE_RANGE = 20

ITEM_NAMES_TO_DESCRIPTIONS = {
    ITEM_DUCT_TAPE: 'repair ' + str(REPAIR_AMOUNT) + ' damage',
    ITEM_EXTRA_BATTERY: 'power +' + str(BATTERY_POWER) + ', ' + str(BATTERY_DURATION) + ' TUs',
    ITEM_RED_PAINT: 'quadruple speed, 300 TUs',
    ITEM_EMP: 'disable enemies, radius ' + str(AREA_DISABLE_RANGE)
}
